name: Terraform GCP

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  terraform:

    runs-on: [self-hosted, Linux, X64,uat]
    # UAT deployment
 

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Terraform
        run: terraform version

      - name: Check GCP
        run: gcloud version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
